### ISSUE TITLE
Create documentation website

### ISSUE THREAD

**Issue by npeltier** [adobe/adobe-dx#1]
first step before this repo is being usable would be to create an adobe-dx documentation website using adobe-dx, so we know it "works"

**Comment by filmaj** [comment]
Just a note that if you publish to this project's github pages, it will be available  at https://opensource.adobe.com/adobe-dx. Some projects find that convenient. That is all!

**Comment by npeltier** [comment]
thanks @filmaj i know we can do that, but we need a public sample usage of this repo :-) may be we'll end up with documentation in several places depending of what it's documenting

**Comment by auniverseaway** [comment]
Docs exists!
