### ISSUE TITLE
Add a generic caconfig retriever utility

### ISSUE THREAD

**Issue by chrischrischris** [adobe/adobe-dx#111]
As pointed out in [this comment](https://github.com/adobe/adobe-dx/pull/110#pullrequestreview-431760842) the `resolveGradient` method in BackgroundGradient.java has no need to be specific to gradients.

That file should be removed in favor of a `ContextAwarePropertyRetriever` utility that can be used to retrieve any caconfig value.

**Comment by npeltier** [comment]
working on GH-24, i think i found a nice way, let's see if that work, and then close this one

**Comment by npeltier** [comment]
so @auniverseaway saw GH-24's StyleGuide, and i guess we're ok removing BackgroundGradientModel. will do that tomorrow
