### ISSUE TITLE
Docs available on AEM as a Cloud Service

### ISSUE THREAD

**Issue by auniverseaway** [adobe/adobe-dx#124]
Make Dx Docs available on AEM as a Cloud Service

**Comment by janaki-r-bhagwath** [comment]
Resolved by - https://github.com/adobe/adobe-dx/commit/757310320f7bf097ac35cd9e10a6aac41763e3f2
Currently in `aemaacs` branch.  @npeltier and @auniverseaway - if all the other changes look okay - then we can merge it to master.

**Comment by npeltier** [comment]
@janaki-r-bhagwath cc @auniverseaway i wonder if we want the full repo in `aemaacs` branch, or "just" the docs application, that would be a sample usage, without having to build the rest (if i manage to fix #125), we would have some process that for any update of docs folder in master branch, would merge it in aemaacs branch automatically or manually

**Comment by npeltier** [comment]
so @janaki-r-bhagwath @auniverseaway i plan to try tomorrow to narrow aemaacs branch to be some kind of mix between aemaacs uber jar & our fresh new released deps, as a consuming app

**Comment by npeltier** [comment]
here we are, guess we'll be ready once deps are all on central @janaki-r-bhagwath @auniverseaway not even sure we need sdk-api dep

**Comment by npeltier** [comment]
latest deployment was created with docs only @janaki-r-bhagwath @auniverseaway

**Comment by npeltier** [comment]
i guess this can be closed now, as we do have this available. Further work for eventual automation or new instances will have new issues
