### ISSUE TITLE
find a way to embed new devs and discuss

### ISSUE THREAD

**Issue by npeltier** [adobe/adobe-dx#13]
for now we have one admin team and no real way but github issues to discuss openly.

**Comment by npeltier** [comment]
Hey @filmaj we are looking for an open discussion place, and github teams might be a nice way: could you create another team admins have rights on? adobe-dx-dev that has write access but not admin access on the repository? then we can eventually create child teams of etc...but it looks we can't create one right now.

**Comment by filmaj** [comment]
@adobe/adobe-dx-devs is created and existing members from @adobe/adobe-dx-admins are added. -devs has Write access to this repo.

Closing this but if anything else is needed feel free to ping me.

**Comment by npeltier** [comment]
thanks @filmaj ! https://github.com/orgs/adobe/teams/adobe-dx-devs/discussions works great!
