### ISSUE TITLE
cannot build the main project

### ISSUE THREAD

**Issue by coatpont** [adobe/adobe-dx#186]
### Expected Behaviour

mvn clean install should work

### Actual Behaviour

[ERROR] Failed to execute goal on project testing: Could not resolve dependencies for project com.adobe.dx:testing:jar:0.1.1-SNAPSHOT: Failure to find org.apache.commons:commons-imaging:jar:1.0-R1534292 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

### Reproduce Scenario (including but not limited to)

Just a regular mvn clean install

**Comment by npeltier** [comment]
thanks @coatpont it looks like the specified version is specific to adobe public repository for some reason

```
INFO] ------------------------< com.adobe.dx:testing >------------------------
[INFO] Building Adobe DX - Testing 0.1.1-SNAPSHOT                        [5/24]
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from adobe-public-releases: https://repo.adobe.com/nexus/content/groups/public/org/apache/commons/commons-imaging/1.0-R1534292/commons-imaging-1.0-R1534292.pom
Downloaded from adobe-public-releases: https://repo.adobe.com/nexus/content/groups/public/org/apache/commons/commons-imaging/1.0-R1534292/commons-imaging-1.0-R1534292.pom (13 kB at 8.5 kB/s)
Downloading from adobe-public-releases: https://repo.adobe.com/nexus/content/groups/public/org/apache/commons/commons-imaging/1.0-R1534292/commons-imaging-1.0-R1534292.jar
Downloaded from adobe-public-releases: https://repo.adobe.com/nexus/content/groups/public/org/apache/commons/commons-imaging/1.0-R1534292/commons-imaging-1.0-R1534292.jar (716 kB at 134 kB/s)
```
i'll change the version to 1.0-alpha2 as referred in the project page https://commons.apache.org/proper/commons-imaging/download_imaging.cgi

**Comment by npeltier** [comment]
unfortunately @coatpont it looks like a transitive dependency of the uber jar dependency, so i can't do  much at this stage. Can you please add `https://repo.adobe.com/nexus/content/groups/public` to your maven repos?
