### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by yesil** [adobe/adobe-dx#190]
The build in my branch is failing because of a crypto related test that doesn't fail in vscode, any suggestion?

![image](https://user-images.githubusercontent.com/330057/118017310-c0e93380-b356-11eb-85d4-30e47e7ae6da.png)

`[main] ERROR com.adobe.dx.admin.servlet.EncryptionServlet - Error in Encryption Servlet: Request Param missing`

https://github.com/adobe/adobe-dx/pull/188/checks?check_run_id=2568490405#step:4:1938

**Comment by npeltier** [comment]
@yesil you have been fooled by the fact the test is spitting out an exception but actually it's running fine.
i'd rather check at your new code's coverage:
Error:  Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.3:check (check-coverage) on project content.core: Coverage checks have not been met. See log for details. -> [Help 1]
just add `jacoco-report` profile, and you should see that error in vs code too...
