### ISSUE TITLE
CI Integration

### ISSUE THREAD

**Issue by auniverseaway** [adobe/adobe-dx#2]
### Expected Behaviour
As a developer, I would like a CI service to build my branch for which my PR is based on so that it can check for:

1) Unit test coverage (Java & Javascript)
2) Security vulnerabilities (as described by Cloud Manager rules)
3) Ability to compile

### Actual Behaviour
There is no CI service.

### Reproduce Scenario (including but not limited to)
1) Submit a PR

#### Steps to Reproduce
1) Submit a PR

#### Platform and Version
All

#### Sample Code that illustrates the problem
None

#### Logs taken while reproducing problem
Submitted PR

**Comment by npeltier** [comment]
@auniverseaway should we give a try to githubactions?

**Comment by auniverseaway** [comment]
I think so.

**Comment by npeltier** [comment]
@auniverseaway pls have a look at https://github.com/adobe/adobe-dx/runs/446514339 a build is triggered for any push or pull request.
Will resume my work on this by adding unit test &[ codecov action](https://github.com/codecov/codecov-action) in the workflow which should close this issue.

**Comment by npeltier** [comment]
@auniverseaway i think we might run into some issues having *exactly* the same coverage as cloud manager, as i don't see an easy "free" way to integrate (all custom rules cloud manager runs) [https://docs.adobe.com/content/help/en/experience-manager-cloud-manager/using/how-to-use/understand-your-test-results.html]. May be running with default + some rules (basically findbugs ones could be added) is ok for now?

**Comment by npeltier** [comment]
@auniverseaway problem found with github actions is PR can't access repo's secrets. Hence you can't have nice sonarcloud reports for each PR made (just once commit gets actually in the repo's branch)

**Comment by npeltier** [comment]
let's call it done for now, i'm sure it will evolve but we have all we needed in the initial description
