### ISSUE TITLE
Abstraction for breakpoint service.

### ISSUE THREAD

**Issue by auniverseaway** [adobe/adobe-dx#43]
As a developer I want a service to provide me with proper breakpoint fallbacks for the property I provide so that I do not have to re-implement my own breakpoint fallbacks for each property individually.

### Context
We have background color, foreground color, background image, and spacing that all need this service. We should be able to ask for a property (padding left) and the current breakpoint (desktop) and if the the property doesn't exist, it is probably empty so that tablet, mobile can still exist but we're not outputting unnecessary code.

**Comment by npeltier** [comment]
@auniverseaway @chrischrischris this might need some JS magic for the dialogs: we could mark a fieldset with "enable-breakpoints" (or better name) and this would get the ordered list of breakpoint name, duplicate the field set accordingly, and prefix fields names, wdyt?

**Comment by auniverseaway** [comment]
I view the property creation of values being separate from the retrieval. The amount of Coral hacking to do the above does not sound appetizing.

I do think you have a good point that a consumer may not want the complexity of a multi-breakpoint solution. I.E. different background images.

Wondering if there's something we could do to satisfy the second without having to get really deep into Coral hacking.

**Comment by npeltier** [comment]
okay, let's leave it here for now.
@auniverseaway do we go with mobile -> tablet -> desktop hardcoded for now too?

**Comment by auniverseaway** [comment]
Initially I'm thinking...

Mobile (default)
Tablet (if no value, return null)
Desktop (if no value return null)

And yeah, for the dialogs... probably hardcoded unless we do something in the content policy to enable breakpoints. Might be a cheap way to get reduced complexity for consumers who don't need it.
