### ISSUE TITLE
ID Service

### ISSUE THREAD

**Issue by auniverseaway** [adobe/adobe-dx#45]
Something to generate CSS IDs. Must be unique and not cause collisions on page.

On private Dexter, we went with something based on path and hashed it.

`/content/xfs/my-xf/master/jcr:content/my-component` > `ee2b49d80498e239dcc727c355611696`

I think there was some stumbling with this approach. @sabyamon may know more details as he dealt with this a bunch.

**Comment by auniverseaway** [comment]
Another talking point: ID stability should be considered regardless of node / path structure.

By default, Target likes to use IDs when it finds them and if a page is refactored, it would be ideal if  the ID does not change to Target has a chance of continuing to run a test.

**Comment by npeltier** [comment]
@auniverseaway so we should rather add a unique enough property "id" at node creation we can access through property, right?

**Comment by npeltier** [comment]
nope, as this will not work with live copies...
