### ISSUE TITLE
dx_id should not start with a number

### ISSUE THREAD

**Issue by auniverseaway** [adobe/adobe-dx#75]
While writing FlexModel, I realized the ID service can generate an id that starts with a number. This is not compliant with the ID property for HTML.

We could:

1) Prefix in our classes ("d" + id)
2) Change the ID service.

For now I am going to prefix.

**Comment by npeltier** [comment]
isn't this only an HTML4 constraint? (will add a "d" that's fine i guess)

**Comment by npeltier** [comment]
@auniverseaway agrees on closing this https://github.com/adobe/adobe-dx/pull/77
