### ISSUE TITLE
"all" package is outdated

### ISSUE THREAD

**Issue by npeltier** [adobe/adobe-dx#84]
all package points to 0.0.1-SNAPSHOT versions. We should 
1. decide wether latest "all" points to the latests, or to the latest releases,
2. update accordingly

cc @adobe/adobe-dx-devs

**Comment by auniverseaway** [comment]
1. All latests of the local repo.

We ran into this after publishing admin. The local repo would not install / build admin and thus break dx-docs.

**Comment by npeltier** [comment]
lgtm now, plus #124 made docs not a dependency of all anymore (which saves us a round of release)
