### ISSUE TITLE
Modularize Adobe Fonts outside Configuration Manager

### ISSUE THREAD

**Issue by auniverseaway** [adobe/adobe-dx#9]
### Expected Behaviour
As a developer I expect Adobe Fonts configuration should be de-coupled from Configuration Manager so I can release each feature independently.

### Actual Behaviour
Adobe Fonts configuration code resides in Config Manager.

**Comment by npeltier** [comment]
while having 2 packages make sense here, i wonder if we should with one bundle per module, or, e.g. having an "admin" module cc @adobe/adobe-dx-admins

**Comment by abani-github** [comment]
👍 for modularisation. the important factor will be the classification of modules

**Comment by npeltier** [comment]
with 24be7fe3e02be, opted for a broader modularisation, keeping together fonts and config manager
